### ISSUE TITLE
example 工程无法运行,提示 'React/RCTRootView.h' file not found

### ISSUE THREAD

**Issue by JxJPu9bD** [chameleon-team/chameleon-sdk-ios#1]
![image](https://user-images.githubusercontent.com/12554248/53379066-005c1d00-39a3-11e9-84df-5789a60de506.png)
![image](https://user-images.githubusercontent.com/12554248/53379105-2b467100-39a3-11e9-959f-7d917c36c4c4.png)
查看发现 podspec 的依赖中没有加入 React,这样写好像是有问题都

**Comment by JxJPu9bD** [comment]
同时 使用 pod lib lint --verbose 也会不通过
发现 weex 也没有加入到依赖里
也会报错.

**Comment by JxJPu9bD** [comment]
我把依赖改为    
    s.dependency 'JSONModel'
    s.dependency 'Masonry', '~> 0.6.3'
    s.dependency 'WeexSDK', '~> 0.19.0.2'
    s.dependency 'SocketRocket'
    s.dependency 'SDWebImage', '3.7.6' 
    s.dependency 'React'
    s.dependency 'yoga'
    s.dependency 'DoubleConversion'
    s.dependency 'glog'
    s.dependency 'Folly'

能够运行 Demo 了

**Comment by kachihaha** [comment]
我们移除了对RN的依赖。
