### ISSUE TITLE
SDK  bug

### ISSUE THREAD

**Issue by xztl** [chameleon-team/chameleon-sdk-ios#4]
iOS sdk 不能pod 线上 直接导入么?  下载sdk导入环境依赖性太强了，且没法只导入weex库，必须同时导入RN库，请问能处理下么? 另外下载的源码pod依赖有问题，运行不起

**Comment by kachihaha** [comment]
目前已经移除了对RN的支持；
SDK线上需要发布至Pod公共源，目前正在做。
